trigger: none

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: DownloadGitHubRelease@0
  displayName: 'Download Release'
  inputs:
    connection: 'github.com_lmarqs'
    userRepository: 'tecidosbr/gestao-processos'
    defaultVersionType: 'latest'
    itemPattern: '*.zip'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Avaliação Gratuita(60b55c61-13b2-4600-869e-7aa1d496e967)'
    appType: 'webApp'
    WebAppName: 'gestao-processos-webapp'
    packageForLinux: '$(System.ArtifactsDirectory)/gestao-processos-webapp-*.zip'
    ScriptType: 'Inline Script'
    InlineScript: 'mv package/build/* .'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
    RemoveAdditionalFilesFlag: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Avaliação Gratuita(60b55c61-13b2-4600-869e-7aa1d496e967)'
    appType: 'functionApp'
    WebAppName: 'gestao-processos-service'
    packageForLinux: '$(System.ArtifactsDirectory)/gestao-processos-service-*.zip'