trigger: none
pr: none

pool:
  vmImage: 'vs2017-win2016'

steps:

- task: DownloadGitHubRelease@0
  displayName: 'Download Release'
  inputs:
    connection: 'lmarqs'
    userRepository: 'tecidosbr/gestao-processos'
    defaultVersionType: 'latest'
    itemPattern: '*.tgz'
    downloadPath: '$(Agent.TempDirectory)'

- task: Bash@3
  displayName: 'Prepare Webapp'
  inputs:
    targetType: 'inline'
    script: 'mkdir webapp && tar -xf *-webapp-*.tgz -C webapp'
    workingDirectory: '$(Agent.TempDirectory)'

- task: Bash@3
  displayName: 'Prepare Service'
  inputs:
    targetType: 'inline'
    script: 'mkdir service && tar -xf *-service-*.tgz -C service'
    workingDirectory: '$(Agent.TempDirectory)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Avaliação Gratuita(1)(60b55c61-13b2-4600-869e-7aa1d496e967)'
    appType: 'webApp'
    WebAppName: 'gestao-processos-webapp'
    packageForLinux: '$(Agent.TempDirectory)/webapp'
    ScriptType: 'Inline Script'
    InlineScript: 'mv package/* package/.* .'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
    RemoveAdditionalFilesFlag: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Avaliação Gratuita(1)(60b55c61-13b2-4600-869e-7aa1d496e967)'
    appType: 'functionApp'
    WebAppName: 'gestao-processos-service'
    packageForLinux: '$(Agent.TempDirectory)/service'
    ScriptType: 'Inline Script'
    InlineScript: 'mv package/* package/.* .'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
    RemoveAdditionalFilesFlag: true